drop table if exists comments;
drop table if exists bookings;
drop table if exists items;
drop table if exists requests;
drop table if exists users;

create TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(200) NOT NULL,
                                     email VARCHAR(200) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description VARCHAR(512) NOT NULL,
                                        requester_id BIGINT NOT NULL REFERENCES users(id),
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        CONSTRAINT pk_request PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(200) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     owner_id BIGINT REFERENCES users(id),
                                     request_id BIGINT,
                                     CONSTRAINT pk_items PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        text VARCHAR(1024) NOT NULL,
                                        item_id BIGINT NOT NULL REFERENCES items(id),
                                        author_id BIGINT NOT NULL REFERENCES users(id),
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        CONSTRAINT pk_comments PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT NOT NULL REFERENCES items(id),
                                        booker_id BIGINT NOT NULL REFERENCES users(id),
                                        status VARCHAR NOT NULL,
                                        CONSTRAINT pk_bookings PRIMARY KEY (id)
);